name: m3u-editor
services:
  m3u-editor:
    image: #need to build one for arm64
    container_name: m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=auto
      - WWWUSER=sail
      - LARAVEL_SAIL=1
      - XDEBUG_MODE=off
      - OCTANE_HTTPS=true #need to enable for https
    volumes:
      - ./config:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
    labels:
      cosmos-force-network-mode: "m3u-editor_default"
      cosmos-force-network-secured: "true"
networks: {}
volumes:
  m3u-editor-config:
    name: m3u-editor-config
